### PR TITLE
Fix typos method and parameter

### PR DESCRIPTION
**Pull request by bact**
- <s>enum: `Unkown` -> `Unknown`</s>
- method: `getCaseSensisitiveId` -> `getCaseSensitiveId`
  - parameter: `caseInsensisitiveId` -> `caseInsensitiveId`
- Add default method `getCaseSensisitiveId` with the same parameter spelling `caseInsensisitiveId` for backward compatibility
  - This [default method](https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html) is implemented inside the interface, so it will be available to any class implements the interface without the need to actually implemented it (to avoid breaking) 

<s>Note: as the enum and the method are public, this change will break any code that use any of them</s>

Method `getCaseSensisitiveId` is still available and can be called the same way.

Defer the renaming of enum for now, just add a comment to the code.

### CODE REVIEW

**Comment by bact** [comment]
If this change is accepted, further updates of names are needed in https://github.com/spdx/Spdx-Java-Library

**Comment by goneall** [comment]
I'm concerned about the breaking changes to the public methods - so I'll label this for the next major release.

**Comment by bact** [comment]
> I'm concerned about the breaking changes to the public methods - so I'll label this for the next major release.

@goneall I have removed the enum renaming and add the default method to the interface (per discussion here: https://github.com/spdx/Spdx-Java-Library/issues/266#issuecomment-2552706391 ) - will this address the backward compatibility concern?

**Review by goneall — APPROVED** [review]
Looks like this should work - I'll go ahead and approve / merge in.  If it turns out to break something downstream, we can fix it before the next release.

**Pull request merged**
